spring.application.name=career-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/skillsphere
spring.datasource.username=postgres
spring.datasource.password=@111*Aim

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/skillsphere