spring.application.name=nexus

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsphere
spring.datasource.username=postgres
spring.datasource.password=@111*Aim

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.error.include-message=always
server.error.include-binding-errors=always

server.port=8082

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/skillsphere